-- Deprecated.
-- The project pivoted from demo/runtime tables to the normalized paper experiment schema in V1.
-- Do not create the old `document_chunks` table for new paper experiments.
-- This file is intentionally a no-op so old migration references do not create legacy tables.
