create table if not exists documents (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    source_path varchar(512) not null,
    content_type varchar(50) not null,
    created_at timestamp not null default current_timestamp
);

create table if not exists document_chunks (
    id bigint generated by default as identity primary key,
    document_id bigint not null references documents(id) on delete cascade,
    chunk_index integer not null,
    content text not null,
    page_number integer,
    section_name varchar(255),
    embedding text not null,
    created_at timestamp not null default current_timestamp
);

create table if not exists chat_logs (
    id bigint generated by default as identity primary key,
    question text not null,
    answer text not null,
    answer_mode varchar(50) not null,
    retrieval_status varchar(50) not null,
    source_labels text,
    ip_address varchar(100),
    session_id varchar(100),
    created_at timestamp not null default current_timestamp
);
