create table if not exists documents (
    id bigint generated by default as identity primary key,
    index_name varchar(120),
    corpus_profile varchar(50),
    index_version varchar(100),
    title varchar(255) not null,
    source_path varchar(512) not null,
    content_type varchar(50) not null,
    url varchar(1024),
    posted_at timestamp,
    created_at timestamp not null default current_timestamp
);

create table if not exists document_chunks (
    id bigint generated by default as identity primary key,
    document_id bigint not null references documents(id) on delete cascade,
    chunk_index integer not null,
    content text not null,
    page_number integer,
    section_name varchar(255),
    embedding text not null,
    embedding_model varchar(120),
    embedding_dim integer,
    index_version varchar(100),
    created_at timestamp not null default current_timestamp
);

create table if not exists chat_logs (
    id bigint generated by default as identity primary key,
    question text not null,
    answer text not null,
    answer_mode varchar(50) not null,
    retrieval_status varchar(50) not null,
    source_labels text,
    generation_provider varchar(50),
    generation_model varchar(120),
    generation_model_version varchar(160),
    generation_temperature double precision,
    generation_max_output_tokens integer,
    prompt_version varchar(120),
    input_tokens integer,
    output_tokens integer,
    total_tokens integer,
    estimated_cost_usd double precision,
    ip_address varchar(100),
    session_id varchar(100),
    created_at timestamp not null default current_timestamp
);

create table if not exists index_metadata (
    id bigint generated by default as identity primary key,
    index_name varchar(120) not null,
    corpus_profile varchar(50) not null,
    index_version varchar(100) not null,
    document_count integer not null,
    chunk_count integer not null,
    embedding_model varchar(120) not null,
    embedding_dim integer not null,
    chunk_size integer not null,
    chunk_overlap integer not null,
    tokenizer varchar(120) not null,
    corpus_hash varchar(64) not null,
    retrieval_config_hash varchar(64) not null,
    source_data_path varchar(512) not null,
    created_at timestamp not null default current_timestamp
);

create table if not exists bm25_index_metadata (
    id bigint generated by default as identity primary key,
    corpus_profile varchar(50) not null,
    index_version varchar(100) not null,
    tokenizer varchar(120) not null,
    document_count integer not null,
    chunk_count integer not null,
    corpus_hash varchar(64) not null,
    created_at timestamp not null default current_timestamp
);

create table if not exists retrieval_logs (
    id bigint generated by default as identity primary key,
    question text not null,
    retrieval_method varchar(80) not null,
    index_version varchar(100) not null,
    fusion_method varchar(80),
    chunk_id bigint,
    document_id bigint,
    title varchar(255),
    url varchar(1024),
    posted_at timestamp,
    bm25_score double precision,
    dense_score double precision,
    hybrid_score double precision,
    bm25_rank integer,
    dense_rank integer,
    hybrid_rank integer,
    created_at timestamp not null default current_timestamp
);
